# Generated by Django 4.2.7 on 2023-11-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_like_article_alter_like_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_cover',
            field=models.ImageField(blank=True, upload_to='covers'),
        ),
    ]
